Repository soool22/2025-likelion-ds3, pull requests merged in 2025-08, with the labels that each got.

#74 [feat, style]내 포인트, 기프티콘 샵 등 연동
  HTML/GifticonShop.html
  HTML/MyCoupon.html
  HTML/MyEditPage.html
  HTML/MyPoint.html
  HTML/ReviewBest.html
  HTML/Top100.html
  accounts/templates/accounts/profile_edit.html
  static/CSS/GifiticonShop.css
  static/CSS/MyPoint.css
  static/CSS/Top100&ReviewBest.css
  static/IMG/blue-time.svg
  static/IMG/charactericon.png
  static/IMG/pen.png
  static/js/GifticonShop.js
  static/js/MyPoint.js
  stores/templates/stores/popular-store-list.html
  stores/templates/stores/public-store-list.html
  stores/templates/stores/review-best-list.html
  stores/views.py
  visit_rewards/templates/visit_rewards/gifticon_shop.html
  visit_rewards/templates/visit_rewards/my_rewards.html
Labels: feat, style

#87 [fix] QR 발급기능 점주 가게 상세로 이동 및 일부 수정
  stores/templates/stores/owner-qr.html
  stores/templates/stores/owner-store-detail.html
  stores/urls.py
  stores/views.py
  visit_rewards/utils.py
  visit_rewards/views.py
Labels: fix

#91 [feat,fix] 알림 센터 페이지 연결, ai 프롬프트 수정, 관심매장 css 수정
  accounts/templates/accounts/favorite_stores.html
  accounts/views.py
  ai_services/services.py
  home/templates/home/alarmcenter.html
  home/templates/home/main.html
  home/urls.py
  home/views.py
  static/CSS/InterestingStore.css
Labels: feat, fix
